FROM --platform=$BUILDPLATFORM docker.io/library/node:26.4.0-alpine@sha256:725aeba2364a9b16beae49e180d83bd597dbd0b15c47f1f28875c290bfd255b9 AS build
WORKDIR /app

ENV CYPRESS_INSTALL_BINARY=0

COPY package*.json ./
COPY patches/ ./patches/
RUN npm ci
COPY . .
RUN NODE_ENV=production npm run build:with-font


FROM docker.io/library/caddy:2.11.4-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648
EXPOSE 80

COPY build/docker/Caddyfile.local /etc/caddy/Caddyfile
COPY --from=build /app/dist /usr/share/caddy
